zhome=$(dirname $(realpath ~/$(readlink ~/.zshrc)))
zinstalls=$zhome/zinstalls

#create user bin dir if not any exist
if [ ! -d ~/bin ];then
  mkdir ~/bin
fi

# create zinstalls if not exist
if [ ! -d $zinstalls ];then
  mkdir $zinstalls
fi

# scan zpath and add to path
if [ -f $zhome/zpath ];then
  for pathCandidate in $(cat $zhome/zpath 2>/dev/null || echo);do
    pathCandidate=$(eval echo $pathCandidate)
    if [ -d "$pathCandidate" ];then
      export PATH="$pathCandidate:$PATH"
    fi
  done
fi

# zsources
if [ -f $zhome/zsources ];then
  for toSource in $(cat $zhome/zsources 2>/dev/null || echo);do
    toSource=$zhome/zinits/$toSource
    if [ -f $toSource ];then
      source $toSource "$(cat $toSource-config 2>/dev/null || echo)"
    else
      echo "$toSource not found => not sourced" >2
    fi
  done
fi

unset zhome
unset zinstalls
