function {
  local zhome=$(dirname $(realpath ~/$(readlink ~/.zshrc)))
  local zinstalls=$zhome/installs

  # sources
  if [ -f $zhome/sources ];then
    for toSource in $(cat $zhome/sources 2>/dev/null || echo);do
      local configFile=$zhome/configs/$toSource
      local toSource=$zhome/inits/$toSource
      if [ -f $toSource ];then
        local configArgs=()
        if [ -f $configFile ];then
          while read configArg;do
            configArgs+=("$configArg")
          done <$configFile
        fi
        source $toSource $configArgs
      else
        echo "$toSource not found => not sourced" >2
      fi
    done
  fi
}
